### ISSUE TITLE
Tiles not being supplied over HTTPS in node.js

### ISSUE THREAD

**Issue by skuderos** [b-g/tilehut#16]
Hello, 

I have a set of maptiles that are properly being served up over http (both in localhost and by accessing remotely), but I can't for the life of me figure out how to get them to be served over https. I have a node.js server set up that has tilehut running, and supplied maptiles both over http and https. As you can guess, the http version serves them properly whereas the https version serves a blank page anytime I try to request a specific tile or preview a map. I have tried to find a solution for months but unfortunately, without success.

**Comment by skuderos** [comment]
After some more testing, I am getting a bit closer as to why it suddenly stops working over https. As I mentioned in the previous comment, serving the tiles over http works without any issues. When trying to load my map over https I for some reason keep getting 404 responses to any tile request. I decided to open the console and have a look at each individual tile request. What I noticed is that the z/x/y _coordinates_ that are being requested do not match up to the ones that are requested over http. When I copy the url for a specific tile that works in the http version (for example, .../ehaa_256/11/1056/673.png) and then load that over the https version,  I get the correct image of the correct tile. When checking the request that gets sent out from the HTTPS version, I notice that the x and y values are often significantly higher than I would expect them to be on that particular section of map (for example, .../ehaa_256/13/4234/2695.png). This set of coordinates does not make sense, and I imagine this is the reason for my troubles. 

This means there is no problem with data not being presented properly over https or something along those lines. What I now need to figure out is _why_ the https request changes the coordinates that tiles are being requested for.

**Comment by skuderos** [comment]
I have found the solution! In retrospect, it was pretty simple and had nothing to do with the coordinates... 

All I needed to do was set the response header for tilehut to state access-control-allow-origin, anonymous. (res.header('Access-Control-Allow-Origin', 'anonymous');)

**Comment by b-g** [comment]
Hi @skuderos, sorry for the slow response! Very busy here with the start of the semester ... Glad that you figured it out! Congrats! Could you share the exact lines in case someone else has trouble with the same issue? I guess it is here, or?

https://github.com/b-g/tilehut/blob/377330b24cc3ef02946b92a06e8ca2c768ef2236/server.js#L46-L51
