### ISSUE TITLE
Choose a licence?

### ISSUE THREAD

**Issue by robpvn** [b-g/tilehut#2]
Hi, I think tilehut looks like a great tool for checking out tilesets and also for learning a bit about how things work by reading the code. But I can't find any mention of a licence anywhere in the repository. It would be very helpful if [you chose a licence](http://choosealicense.com/) and applied it to the repository so that others can build on your great work!

**Comment by b-g** [comment]
Hi @robpvn!

Thanks for the push! :)

@joeyklee @stephanbogner, I would vote for MIT License ... you guys?

B

**Comment by joeyklee** [comment]
Hi B,

Yes, this works for me! 

Best,
J

**Comment by stephanbogner** [comment]
Cool with me as well!

**Comment by b-g** [comment]
Went for BSD to be compatible with "node-mbtiles" ...
