### ISSUE TITLE
some maps do not render properly

### ISSUE THREAD

**Issue by ianhuynh** [b-g/tilehut#6]
Env:  OSX El Capitan, Chrome: Version 56.0.2924.87 (64-bit) 
 
http://localhost:8000/tiles-world-simple/map works  but http://localhost:8000/tiles-work-vector/map  fails on error below

Error: Failed to initialize WebGL
_setupPainter — map.js:1100
e — map.js:168
createVectorMap — map:202
createMapFromType — map:155
init — map:142
(anonymous function) — map:236
j — jquery-2.1.1.min.js:2:26866
fireWith — jquery-2.1.1.min.js:2:27675
x — jquery-2.1.1.min.js:4:11132
(anonymous function) — jquery-2.1.1.min.js:4:14769

i have verified that Chrome WebGL flags are set to 'enabled'  

This also failed on Safari.

**Comment by joeyklee** [comment]
Hi @ianhuynh - thanks for your message. I'm not sure if you resolved this yet, but it seems your link is incorrect.

"work" ==> "world" 
http://localhost:8000/tiles-work-vector/map  ==> http://localhost:8000/tiles-world-vector/map 

Please try the link with the correct url above. Cheers!

**Comment by b-g** [comment]
As no feedback ... I guess this can be closed.
