### ISSUE TITLE
Update "Your Own Hosted Tileserver in 5 Minutes" (alternative to openshift) 

### ISSUE THREAD

**Issue by b-g** [b-g/tilehut#7]
Hi @joeyklee I believe you looked into hosting tilehut alternative to openshift recently, or? If so, could you update the section in the readme? https://github.com/b-g/tilehut#your-own-hosted-tileserver-in-5-minutes Best, B

**Comment by joeyklee** [comment]
There's a few options: 
- Heroku
- Digital Ocean

I guess hosting big tiles in Heroku is not so great, but for smaller, quick and dirty prototypes, maybe it is ok - the advantage is that it is super easy, just storage of those data in the version control is not a good idea. Documentation for Heroku deployment is here: https://github.com/joeyklee/hello-vector-tiles#part-5-deploy-tilehut-and-show-the-world-your-maps 

Digital ocean takes more setup and some trickier concepts, but I've documented that here: https://github.com/ubccalp/tileserver/blob/master/README-DigitalOcean-Setup.md

When I manage the time, I can figure out the best way to replace the openshift documentation for Tilehut.

**Comment by joeyklee** [comment]
Should be done now with: https://github.com/b-g/tilehut/commit/6c1feec9e90e27b44650da547ef9fe61791ef026 Thanks!
